apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    app: static-web
    role: myrole
spec:
  containers:
    - name: web
      #image: nginx
      image: nginxinc/nginx-unprivileged
      ports:
        - name: web
          containerPort: 80
          protocol: TCP