apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}-config-map"
  labels:
    app: {{ .Release.Name }}
    {{- include "helm.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.environmentVariables }}
  {{ $key }}: {{ $value | quote }}
{{- end }}