{{- if .Values.route.enabled }}
  {{ $appname := include "helm.fullname" . }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .Release.Name }}
    {{- include "helm.labels" . | nindent 4 }}
  name: {{ .Chart.Name }}-route
spec:
  {{- if .Values.route.name }}
host: {{ .Values.route.name }}.{{ .Values.route.domain }}
  {{- else }}
host: {{ .Release.Name }}-{{ .Release.Namespace }}.{{ .Values.route.domain }}
  {{- end }}
  {{- if .Values.contextPath }}
path: {{ .Values.contextPath }}
  {{- end }}
port:
  targetPort: http
to:
  kind: Service
  name: {{ $appname }}
tls:
  termination: edge
  insecureEdgeTerminationPolicy: Redirect
  {{- end }}