apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    app: {{ .Release.Name }}
    {{- include "helm.labels" . | nindent 4 }}
stringData:
  {{- toYaml .Values.secretEnvironmentVars | nindent 2 }}